general {
	before_sleep_cmd = qs ipc call lockscreen lock
}

listener {
	timeout = 300
	on-timeout = qs ipc call lockscreen lock
}

listener {
    timeout = 420                                                                                  
    on-timeout = brightnessctl set 5% 
}
