background = 0xFF{{background | strip}}
base = 0xFF{{color0 | strip}}
text = 0xFF{{color15 | strip}}
alternate_base = 0xFF{{color1 | strip}}
bright_text = 0xFF{{forground | strip}}
accent = 0xFF{{color3 | strip}}
accent_secondary = 0xFF{{color8 | strip}}
